//This entity describes the Elementary based Ring Oscillator entropy source. The signal generated by RO0/div is used to sample RO1. The ERO output data is synchronized with the output clock 'clk'

module ero #(
  parameter REG_WIDTH = 32                      //Width for the configuration registers
)(
  input reset,                                  //Asynchronous reset
  input ro0,                                    //Sampling ring-oscillator input
  input ro1,                                    //Sampled ring-oscillator input
  input [REG_WIDTH -1:0] divider,               //Clock division factor for the second ringo
  input changed,                                //Enable strobed when divider value changes

  output clk,                                   //Clock output (equal to ro0/div)
  output reg data,                              //Entropy source data output
  output valid                                  //Valid signal for 'data'
);

//This architecture implements the RTL version of ERO

wire ro0_div;

clkdivider #(                                    //Divide RO0 clock by the divider factor
  .FACTOR_WIDTH(32)
) u_clkdivider(
  .reset(reset),
  .original(ro0),
  .divider(divider),
  .changed(changed),
  .divided(ro0_div)
);


//Sample RO1 with RO0/div
//always @(posedge ro0_div or posedge reset) begin // Simulation error with cocotb by using icarus verilog
//  if (reset)
//    data <= 1'b0; 
//  else
always @(posedge ro0_div) begin
  data <= ro1;           
end

//Output data is syncrhonized with this clock
assign clk = ro0_div;
assign valid = 1'b1;

endmodule
