//This entity describes the Multi Ring Oscillator entropy source. The signal generated by RO0/div is used to sample each ROs RO0 to R0t. The MURO output data is synchronized with the output clock 'clk'.

module muro #(
  parameter REG_WIDTH = 32,             //Width for the configuration registers
  parameter t = 32                      //Number of ROs
)(
  input reset,                          //Asynchronous reset
  input ro0,                            //Sampling ring-oscillator input
  input [t:1] rox,                      //Sampled ring-oscillators input
  input [REG_WIDTH - 1:0] divider,      //Clock division factor for the sampling ringo
  input changed,                        //Enable strobed when divider value changes
  output clk,                           //Clock output (equal to ro0/div)
  output data,                          //Entropy source data output
  output valid                          //Valid signal for 'data'
);

wire ro0_div; // = 1'b0;
reg [t:1] sampled;

//Divide RO0 clock by the divider factor

clkdivider #(
  .FACTOR_WIDTH(32)
)i_clkdivider(
  .reset(reset),
  .original(ro0),
  .divider(divider),
  .changed(changed),
  .divided(ro0_div)
);

//Sample RO1 with RO0/div
always @(posedge ro0_div) begin
  sampled <= rox;
end

//Output data is syncrhonized with this clock
assign clk   = ro0_div;
// for (i = 1; i < t; i=i+1 ) begin
//   if(i = 1) data = sample[1];
//   assign data  =  data ^ sampled [i+1];
// end
assign data = ^sampled;
assign valid = 1'b1;


  
endmodule
