library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_unsigned.all;

-- This entity describes the Elementary based Ring Oscillator entropy source. The signal generated by 'ro0/div' is used to sample 'ro1'. The ERO has a data and a clock output (one data each clk rising edge).
entity ero is
	port (
		-- Sampling ring-oscillator input
		ro0: in std_logic;
		-- Sampled ring-oscillator input
		ro1: in std_logic;
		-- Clock division factor for the second ringo
		div: in std_logic_vector (31 downto 0);
		-- Clock output (equal to ro0/div)
		clk: out std_logic;
		-- Entropy source data output
		data: out std_logic
	);
end entity;

-- This architecture implements the RTL version of ERO.
architecture rtl of ero is

	signal ro0_div: std_logic := '0';

begin

	-- Takes RO0 through the clock divider
	divider: entity work.clkdiv
	generic map (
		FACTOR_WIDTH => 32
	)
	port map (
		original => ro0,
		factor => div,
		divided => ro0_div
	);

	-- Sample RO1 with RO0/div
	process (ro0_div)
	begin
		if rising_edge(ro0_div) then
			data <= ro1;
		end if;
	end process;

	-- Output data is syncrhonized with this clock
	clk <= ro0_div;

end architecture;
