VHDL_SOURCES += ../../hdl/synchronizer.vhd
TOPLEVEL = synchronizer
MODULE = test_synchronizer

SIM_ARGS += -gDATA_WIDTH=32

include ../config.mk
include $(shell cocotb-config --makefiles)/Makefile.sim
