VHDL_SOURCES += ../../hdl/ptrng/conditioner.vhd
TOPLEVEL = conditioner
MODULE = test_conditioner

SIM_ARGS += -gRAND_WIDTH=32

include ../config.mk
include $(shell cocotb-config --makefiles)/Makefile.sim
